### ISSUE TITLE
[FEEDBACK] Gesturefy Major Update 2.0

### ISSUE THREAD

**Issue by Robbendebiene** [Robbendebiene/Gesturefy#314]
## This is a temporary issue where users can leave feedback and share their thoughts about the new Gesturefy version.
PS: I like it more than the old one :-)

**Comment by josh-snoek** [comment]
The close tab gesture does not focus the previous (left) tab when set to previous.

**Comment by Robbendebiene** [comment]
@josh-snoek Thanks, I fixed it.

**Comment by anonymous-d0z42ujxuog5** [comment]
Thanks developer guy for the awesome addon!

**Comment by jdreesen** [comment]
This is really awesome! ❤️  And beautiful, thx for the black theme 😍 

Just one minor issue I spotted while discovering the new possibilities:
The current German translations for `commandDescriptionPopupAllTabs` and `commandDescriptionPopupRecentlyClosedTabs` are reversed. I already reported this via croundin.

**Comment by Ainson** [comment]
Mouse wheel gestures still not able to cycle tabs according to history as Opera perfected all those years ago, but then no other browser or extension have ever been able to so I have anyway resigned it will never happen.

Other than this sorely missed feature, everything looks great. Much more configurable than before, and I like the permissions reduction - it shows respect to users.

Thanks

**Comment by skachcz** [comment]
It would be great if it would be possible to use gestures on "Firefox pages" - pages like Page Source, Page Info, Settings etc.

I understand it's probably limitation given by Firefox itself, but if there would be some way to do it, it would be great.

**Comment by happysurf** [comment]
Thank you very much for the new Gesturefy 2.0.
As first impression, the dark theme is absolutely perfect, the white one is very similar to default theme for that I suggest to replace (or add) a sepia theme like the one in Firefox reader view, very comfortable to the eye.

**Comment by zawor** [comment]
Would be great to have visual indicator on command list telling whether command has advanced settings.

Nevertheless, kudos to you!

**Comment by redactedscribe** [comment]
I think the old gestures set by the user of "Zoom reset" was erroneously translated as "Zoom in" when upgrading to v2. Had to change my gesture back to "Zoom reset".

Also, I think it's not immediately clear how to access a gesture's advanced settings if you already have Gesturefy set up to your liking. Only discovered how to do it when adding new gestures (which I did not actually need). Perhaps advanced settings can be changed post creating them via the Edit gesture pop-up.

It's probably not possible but a small test area on the Settings tab to test your changes to duration, line colour, thickness etc, would be useful.

Thank you for your efforts. A great extension!

**Comment by fule1255** [comment]
Hello.
Thank you for a wonderful add - on.
After updating to version 2, there is something a little troubled.
"Focus tab" can not be set in "Advanced Setting" of "Remove tab".
This feature is one of the reasons I used Gesturefy.
Are you planning to add this feature in the future?

**Comment by Robbendebiene** [comment]
@redactedscribe You are right, it was translated to "Zoom Out". Sorry for that!

@redactedscribe @zawor We thought about that, but then decided against it since you will notice them by creating a gesture. But I totally agree that this is not the case if the gesture is already there.

@fule1255 This should be fixed in Gesturefy 2.0.1 if it's the same problem as @josh-snoek reported.

**Comment by propellaone** [comment]
Hello,
I have an issue when running the add-on "privacy settings" along with Gesturefy. Each time I try to make a gesture a line is drawn to the upper left corner of the screen an an upwards movement is recognized. See screenshot, here I tried to simply go back one page  (middle button and left).  When I disable "websites.ResistFingerprinting" in the privacy settings add-on the problem disappears. I didn't have that problem with the old version of Gesturefy.
![bildschirmfoto 2018-08-10 16 41 29](https://user-images.githubusercontent.com/42275636/43965941-1887c798-9cb0-11e8-9ae5-913e16ec4b3f.png)

**Comment by flowwy** [comment]
Thank you so much for your hard work on Gesturefy!
Complete gestures support (like we used to have...) is the only thing I'm missing in FF and your addon makes the best of the limited API available.

Would it be possible to add an "Open tab in background" command? This would come in very handy to open multiple links from a page in background tabs instead of always having to open a link, switch to the page you opened it from and open the next link in a tab.
Also I was wondering whether it would be possible to have one gesture act differently if it started on a link as opposed to starting not on a link. In the past I used to have the "Down" gesture perform a "Open link in new tab" command if the gesture was started on a link and else (if not started on a link) have it execute the "Open new tab" command.

Thanks!

**Comment by Robbendebiene** [comment]
@propellaone This problem existed in the previous version of Gesturefy too and is also stated in the [add-on description](https://addons.mozilla.org/firefox/addon/gesturefy/). The Mozilla devs already know about this and plan to fix it.

@flowwy This is still possible if you create a gesture with the command "Open link in new tab" and disable the "focus new tab" setting.

**Comment by fule1255** [comment]
@Robbendebiene 
I noticed that there is a command option for each gesture.
I found a setting item.
thanks!

**Comment by propellaone** [comment]
@flowwy Pressing the middle mouse button on a link should do it.

**Comment by Griiid** [comment]
Thanks for making this addon, it's good to use 😃 

Here's a little feature I hope it can be added in:  **increase/decrease text size**.

Now we can increase/decrease all content size, including text and images.  But there's a lot of website that has small size text, and the image size is ok.  That's why I'd like to only increase the text size.

I'm not sure whether this is possible in the newest firefox, if I get something useful, I'll come back and provide them to you 😃 

Thanks.

**Comment by zawor** [comment]
@Robbendebiene actually already defined gesture is one aspect of having indicator... other one which instantly comes to my mind is that it would encourage to tinker around with new gestures which in turns would increase discoverability of more advanced features thus let users to advance towards higher arcane levels (here I have in mind Dreyfus model of skill acquisition but any other will do as well ;)

**Comment by ldgbc** [comment]
Thanks. Too bad Firefox API limitation is restricting it.

**Comment by fule1255** [comment]
Hello.
I used a gesture of "Increasing (decreasing) the numerical value of URL", but I had a little trouble.
In the case where the URL contains more than one numerical value, the numerical value far from the end has been increased / decreased.
Example:
https://xxx.net/xxx1xxx3
(After gesture)
https://xxx.net/xxx2xxx3

I have an request.
In such a case, I would like you to choose which number to increase or decrease.
In my experience, in most cases I would like to increase or decrease the number closer to the end.
Example:
https://xxx.net/xxx1xxx3
(After gesture)
https://xxx.net/xxx1xxx4

**Comment by mattcoz** [comment]
When using a gesture to open a new tab, the location bar is not focused.

**Comment by hewimeddel** [comment]
so... you made a major update but still didn't fix the bug, where the gestures don't work on the start page and some other pages, which nearly everyone uses? Imho, you should get your priorities straight.

**Comment by Itchiii** [comment]
@hewimeddel You mean pages like the addon page of mozilla? Or about:*-tabs? PDFs? 
Then Gesturefy can NOT work there. This is not a bug, but a decision of Mozilla and has been described in many issues as well as in the description. 

> The addon does not work on https://addons.mozilla.org, pure SVG pages and internal pages like most "about:" tabs (e.g. about:newtab, about:addons) or other addon option pages (moz-extension://).

**Comment by happysurf** [comment]
The only workaround is create this new parameter:
**privacy.resistFingerprinting.block_mozAddonManager** and switch to **true.**
Now all extension will work on AMO pages.

**Comment by happysurf** [comment]
> Thanks @happysurf , I've tried it, but however I still can't use Gesturefy on "about:config" page.
I know these two steps were the way to enable extensions, but I failed... is it normal?

Unfortunately is normal on all **about:** pages.

**Comment by Robbendebiene** [comment]
Thank you all for your kind feedback and suggestions for improvement!

**Comment by ldgbc** [comment]
> 
> 
> The only workaround is this :
> 
>     1. Create this new boolean parameter:
>        **privacy.resistFingerprinting.block_mozAddonManager** and switch to **true.**
> 
>     2. Delete all sites inside:
>        **extensions.webextensions.restrictedDomains**.
> 
> 
> Now all extension will work on AMO pages.
> Cons: Impossible to visit Test Pilot web site and no preview for the light themes.

So that was my I couldn't get Test Pilot to work. Thanks. Be good if we can do the same thing for about: pages but who know many years must we wait.

**Comment by hewimeddel** [comment]
Thank you so much happysurf. 
I think Gesturefy should ask users if they want this paternalism and change these settings by installation or at least give users an easy way to change it. 
Not everyone is comfortable with directly changing switches in about:config.

Now  they need to make it work on the standard-startpage and preferences (to me this should have priority, since many people start there) and in those about:* sites (but only a few people go there, so this is not a big thing...).

Who thought that it was a good Idea to block gestures on so many often used pages and especially the built-in pages?
I just don't get why it should matter on which pages i want to use gestures instead of this tiny buttons. Why the hell do they think I install this addon...

This just constantly breaks my workflow and is such a nuisance.

**Comment by happysurf** [comment]
> This just constantly breaks my workflow and is such a nuisance.

For security reason are not allow scripts in AMO pages but also for me this is absurd.
The problem is that Mozilla extension system check is not efficient enough for ensure security, then they prefer completely disable the extensions.
